import os

# Repo root is two directories above this script (.github/scripts/gen_workflows.py)
REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

workflows = [
    ('architect-api-pipeline', 'architect-api', True),
    ('architect-cli-pipeline', 'architect-cli', True),
    ('architect-engine-pipeline', 'architect-engine', True),
    ('architecture-architected', 'plugins/architecture-architected', True),
    ('docs-architected-pipeline', 'plugins/docs-architected', True),
    ('git-architected-pipeline', 'plugins/git-architected', True),
    ('github-architected-pipeline', 'plugins/github-architected', True),
    ('gradle-architected-pipeline', 'plugins/gradle-architected', True),
    ('javascript-architected', 'plugins/javascript-architected', True),
    ('pipelines-architected', 'plugins/pipelines-architected', True),
    ('scripts-architected', 'plugins/scripts-architected', True),
    ('architect-core-pipeline', 'architect-core', False),
    ('architect-cloud-backend', 'architect-cloud/backend', False),
    ('architect-cloud-ui', 'architect-cloud/ui', False),
]

for name, path, has_release in workflows:
    reusable = 'reusable-kotlin-pipeline.yml' if has_release else 'reusable-kotlin-no-release-pipeline.yml'
    lines = [
        "# This file is generated by Architect. Do not edit it directly.",
        "# It will be overwritten by the next Architect run.",
        f"name: {name}",
        "",
        "on:",
        "  push:",
        "    branches:",
        "      - main",
        "    paths:",
        f"      - '{path}/**'",
        "  pull_request:",
        "    branches:",
        "      - main",
        "    paths:",
        f"      - '{path}/**'",
        "",
        "jobs:",
        "  pipeline:",
        f"    uses: ./.github/workflows/{reusable}",
        "    with:",
        f"      module-name: {name}",
        f"      working-directory: {path}",
        "    secrets: inherit",
        "",
    ]
    content = "\n".join(lines)
    filepath = os.path.join(REPO, '.github', 'workflows', f'{name}.yml')
    with open(filepath, 'w') as f:
        f.write(content)
    print(f'Done: {name}.yml')

print('All workflows written.')
