package io.github.architectplatform.cli.plugin

import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory
import com.fasterxml.jackson.module.kotlin.KotlinModule
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.exists
import kotlin.io.path.isDirectory
import kotlin.io.path.name
import kotlin.io.path.readText
import kotlin.io.path.writeText
import kotlin.streams.asSequence

class PluginDocumentationGenerator(
  private val yamlMapper: ObjectMapper = ObjectMapper(YAMLFactory())
    .registerModule(KotlinModule.Builder().build()),
) {
  fun generate(inputPath: Path): PluginDocumentation {
    val pluginRoot = resolvePluginRoot(inputPath)
    val manifestPath = pluginRoot.resolve(MANIFEST_FILE)
    val manifest = yamlMapper.readValue(manifestPath.toFile(), PluginManifest::class.java)
    val tasks = extractTasks(pluginRoot, manifest.template)
    val markdown = buildMarkdown(manifest, tasks)
    val outputPath = pluginRoot.resolve(OUTPUT_FILE)
    outputPath.writeText(markdown)
    return PluginDocumentation(pluginRoot, outputPath, manifest, tasks)
  }

  private fun resolvePluginRoot(inputPath: Path): Path {
    val normalizedPath = inputPath.toAbsolutePath().normalize()
    if (!normalizedPath.exists()) {
      throw IllegalArgumentException("Plugin path does not exist: $normalizedPath")
    }

    return when {
      normalizedPath.isDirectory() -> {
        require(normalizedPath.resolve(MANIFEST_FILE).exists()) {
          "No $MANIFEST_FILE found in $normalizedPath"
        }
        normalizedPath
      }
      normalizedPath.name == MANIFEST_FILE -> normalizedPath.parent
        ?: throw IllegalArgumentException("Cannot resolve plugin root for $normalizedPath")
      else -> throw IllegalArgumentException("Expected a plugin directory or plugin.yml file: $normalizedPath")
    }
  }

  private fun buildMarkdown(manifest: PluginManifest, tasks: List<PluginTaskMetadata>): String {
    val commands = developmentCommands(manifest.template)
    return buildString {
      appendLine("# ${manifest.name} Plugin Reference")
      appendLine()
      appendLine("_Generated by `architect plugin docs`._")
      appendLine()
      appendLine("## Overview")
      appendLine()
      appendLine(manifest.description.ifBlank { "No description provided." })
      appendLine()
      appendLine("## Metadata")
      appendLine()
      appendLine("| Field | Value |")
      appendLine("| --- | --- |")
      appendLine("| Name | `${manifest.name}` |")
      appendLine("| Template | `${manifest.template}` |")
      appendLine("| Version | `${manifest.version}` |")
      appendLine("| Entrypoint | `${manifest.entrypoint}` |")
      appendLine()
      appendLine("## Tasks")
      appendLine()
      if (tasks.isEmpty()) {
        appendLine("No task metadata was detected automatically from the plugin sources.")
      } else {
        tasks.forEach { task ->
          appendLine("### `${task.id}`")
          appendLine()
          appendLine(task.description ?: "No description provided.")
          appendLine()
          appendLine("- Phase: `${task.phase ?: "none"}`")
          appendLine("- Depends On: ${formatDependencies(task.dependencies)}")
          appendLine("- Requires Confirmation: `${task.requiresConfirmation}`")
          appendLine()
        }
      }
      if (commands.isNotEmpty()) {
        appendLine("## Development")
        appendLine()
        appendLine("```bash")
        commands.forEach { appendLine(it) }
        appendLine("```")
      }
    }.trimEnd() + "\n"
  }

  private fun formatDependencies(dependencies: List<String>): String {
    return if (dependencies.isEmpty()) {
      "`none`"
    } else {
      dependencies.joinToString(", ") { "`$it`" }
    }
  }

  private fun developmentCommands(template: String): List<String> = when (template.lowercase()) {
    "kotlin" -> listOf("cd app", "./gradlew build", "./gradlew test")
    "typescript" -> listOf("npm install", "npm run build", "npm test")
    "go" -> listOf("go test ./...", "go build ./...")
    else -> emptyList()
  }

  private fun extractTasks(pluginRoot: Path, template: String): List<PluginTaskMetadata> {
    val extracted = when (template.lowercase()) {
      "kotlin" -> extractKotlinTasks(pluginRoot.resolve("app/src/main/kotlin"))
      "typescript" -> extractTypeScriptTasks(pluginRoot.resolve("src"))
      "go" -> extractGoTasks(pluginRoot)
      else -> emptyList()
    }
    return extracted
      .distinctBy { it.id }
      .sortedBy { it.id }
  }

  private fun extractKotlinTasks(sourceRoot: Path): List<PluginTaskMetadata> {
    return scanFiles(sourceRoot, ".kt") { text ->
      val id = KOTLIN_ID.find(text)?.groupValues?.get(1) ?: return@scanFiles emptyList()
      listOf(
        PluginTaskMetadata(
          id = id,
          description = KOTLIN_DESCRIPTION.find(text)?.groupValues?.get(1),
          phase = normalizePhase(KOTLIN_PHASE.find(text)?.groupValues?.get(1)),
          dependencies = parseQuotedValues(KOTLIN_DEPENDS.find(text)?.groupValues?.get(1).orEmpty()),
          requiresConfirmation = KOTLIN_REQUIRES_CONFIRMATION.find(text)?.groupValues?.get(1)?.toBoolean() ?: false,
        ),
      )
    }
  }

  private fun extractTypeScriptTasks(sourceRoot: Path): List<PluginTaskMetadata> {
    return scanFiles(sourceRoot, ".ts") { text ->
      TYPESCRIPT_TASK_BLOCK.findAll(text).mapNotNull { match ->
        val block = match.value
        val id = TYPESCRIPT_ID.find(block)?.groupValues?.get(1) ?: return@mapNotNull null
        PluginTaskMetadata(
          id = id,
          description = TYPESCRIPT_DESCRIPTION.find(block)?.groupValues?.get(1),
          phase = TYPESCRIPT_PHASE.find(block)?.groupValues?.get(1),
          dependencies = parseQuotedValues(TYPESCRIPT_DEPENDENCIES.find(block)?.groupValues?.get(1).orEmpty()),
          requiresConfirmation = TYPESCRIPT_REQUIRES_CONFIRMATION.find(block)?.groupValues?.get(1)?.toBoolean() ?: false,
        )
      }.toList()
    }
  }

  private fun extractGoTasks(sourceRoot: Path): List<PluginTaskMetadata> {
    return scanFiles(sourceRoot, ".go") { text ->
      GO_TASK_BLOCK.findAll(text).mapNotNull { match ->
        val block = match.value
        val id = GO_ID.find(block)?.groupValues?.get(1) ?: return@mapNotNull null
        PluginTaskMetadata(
          id = id,
          description = GO_DESCRIPTION.find(block)?.groupValues?.get(1),
          phase = GO_PHASE.find(block)?.groupValues?.get(1),
          dependencies = parseQuotedValues(GO_DEPENDENCIES.find(block)?.groupValues?.get(1).orEmpty()),
          requiresConfirmation = GO_REQUIRES_CONFIRMATION.find(block)?.groupValues?.get(1)?.toBoolean() ?: false,
        )
      }.toList()
    }
  }

  private fun scanFiles(sourceRoot: Path, suffix: String, extractor: (String) -> List<PluginTaskMetadata>): List<PluginTaskMetadata> {
    if (!sourceRoot.exists()) {
      return emptyList()
    }

    Files.walk(sourceRoot).use { paths ->
      return paths.asSequence()
        .filter { Files.isRegularFile(it) && it.fileName.toString().endsWith(suffix) }
        .filterNot { it.fileName.toString().contains("Test") }
        .flatMap { extractor(it.readText()).asSequence() }
        .toList()
    }
  }

  private fun parseQuotedValues(rawValue: String): List<String> {
    return QUOTED_VALUE.findAll(rawValue)
      .map { it.groupValues[1] }
      .toList()
  }

  private fun normalizePhase(rawValue: String?): String? {
    return rawValue
      ?.substringAfterLast('.')
      ?.substringBefore('(')
      ?.trim()
      ?.takeIf { it.isNotEmpty() }
  }

  data class PluginDocumentation(
    val pluginRoot: Path,
    val outputPath: Path,
    val manifest: PluginManifest,
    val tasks: List<PluginTaskMetadata>,
  )

  data class PluginManifest(
    val name: String,
    val template: String,
    val version: String,
    val entrypoint: String,
    val description: String = "",
  )

  data class PluginTaskMetadata(
    val id: String,
    val description: String?,
    val phase: String?,
    val dependencies: List<String>,
    val requiresConfirmation: Boolean,
  )

  companion object {
    private const val MANIFEST_FILE = "plugin.yml"
    private const val OUTPUT_FILE = "PLUGIN_REFERENCE.md"

    private val QUOTED_VALUE = Regex("\"([^\"]+)\"")

    private val KOTLIN_ID = Regex("""override\s+val\s+id:\s*String\s*=\s*\"([^\"]+)\"""")
    private val KOTLIN_DESCRIPTION = Regex("""override\s+fun\s+description\(\):\s*String\s*=\s*\"([^\"]+)\"""")
    private val KOTLIN_PHASE = Regex("""override\s+fun\s+phase\(\)\s*=\s*([A-Za-z0-9_.]+)""")
    private val KOTLIN_DEPENDS = Regex("""override\s+fun\s+depends\(\):\s*List<String>\s*=\s*listOf\(([^)]*)\)""")
    private val KOTLIN_REQUIRES_CONFIRMATION = Regex("""override\s+fun\s+requiresConfirmation\(\)\s*=\s*(true|false)""")

    private val TYPESCRIPT_TASK_BLOCK = Regex("""\{[^{}]*id\s*:\s*\"[^\"]+\"[^{}]*}""", RegexOption.DOT_MATCHES_ALL)
    private val TYPESCRIPT_ID = Regex("""id\s*:\s*\"([^\"]+)\"""")
    private val TYPESCRIPT_DESCRIPTION = Regex("""description\s*:\s*\"([^\"]+)\"""")
    private val TYPESCRIPT_PHASE = Regex("""phase\s*:\s*\"([^\"]+)\"""")
    private val TYPESCRIPT_DEPENDENCIES = Regex("""dependencies\s*:\s*\[([^]]*)]""")
    private val TYPESCRIPT_REQUIRES_CONFIRMATION = Regex("""requiresConfirmation\s*:\s*(true|false)""")

    private val GO_TASK_BLOCK = Regex("""\{[^{}]*ID:\s*\"[^\"]+\"[^{}]*}""", RegexOption.DOT_MATCHES_ALL)
    private val GO_ID = Regex("""ID:\s*\"([^\"]+)\"""")
    private val GO_DESCRIPTION = Regex("""Description:\s*\"([^\"]+)\"""")
    private val GO_PHASE = Regex("""Phase:\s*\"([^\"]+)\"""")
    private val GO_DEPENDENCIES = Regex("""Dependencies:\s*\[]string\{([^}]*)}""")
    private val GO_REQUIRES_CONFIRMATION = Regex("""RequiresConfirmation:\s*(true|false)""")
  }
}