package io.github.architectplatform.cli.graph

import io.github.architectplatform.core.project.domain.ProjectDependencyGraph
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.writeText

class ProjectGraphHtmlRenderer {
  fun render(graphName: String, graph: ProjectDependencyGraph): String {
    val mermaid = renderMermaid(graphName, graph)
    val escapedTitle = escapeHtml(graphName)
    return """
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>$escapedTitle Project Graph</title>
    <script type="module">
      import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
      mermaid.initialize({ startOnLoad: true, securityLevel: 'loose' });
    </script>
    <style>
      body {
        font-family: "Iosevka", "IBM Plex Sans", monospace;
        margin: 0;
        padding: 32px;
        background: linear-gradient(180deg, #eef4f1 0%, #dde8e2 100%);
        color: #13201a;
      }
      main {
        max-width: 1400px;
        margin: 0 auto;
      }
      h1 {
        margin: 0 0 12px;
        font-size: 32px;
      }
      p {
        margin: 0 0 24px;
        color: #42554a;
      }
      .card {
        background: rgba(255, 255, 255, 0.72);
        border: 1px solid rgba(43, 76, 60, 0.15);
        border-radius: 24px;
        padding: 24px;
        box-shadow: 0 20px 50px rgba(35, 74, 56, 0.12);
        overflow: auto;
      }
    </style>
  </head>
  <body>
    <main>
      <h1>$escapedTitle Project Graph</h1>
      <p>Generated by Architect from the current project's subproject dependency graph.</p>
      <section class="card">
        <pre class="mermaid">
$mermaid
        </pre>
      </section>
    </main>
  </body>
</html>
""".trimIndent() + "\n"
  }

  fun writeTempFile(graphName: String, graph: ProjectDependencyGraph): Path {
    val outputPath = Files.createTempFile("architect-project-graph-", ".html")
    outputPath.writeText(render(graphName, graph))
    return outputPath
  }

  private fun renderMermaid(graphName: String, graph: ProjectDependencyGraph): String {
    val projects = graph.projects.sorted()
    val mermaidIds = projects.withIndex().associate { (index, project) -> project to "project_$index" }
    val lines = mutableListOf("---", "title: ${graphName} project graph", "---", "flowchart LR")

    projects.forEach { project ->
      lines += "  ${mermaidIds.getValue(project)}[\"${escapeMermaid(project)}\"]"
    }

    graph.dependencies
      .flatMap { (project, dependencies) -> dependencies.map { dependency -> dependency to project } }
      .distinct()
      .sortedWith(compareBy<Pair<String, String>> { it.first }.thenBy { it.second })
      .forEach { (dependency, project) ->
        lines += "  ${mermaidIds.getValue(dependency)} --> ${mermaidIds.getValue(project)}"
      }

    return lines.joinToString("\n")
  }

  private fun escapeMermaid(value: String): String = value
    .replace("\"", "&quot;")
    .replace("<", "&lt;")
    .replace(">", "&gt;")

  private fun escapeHtml(value: String): String = value
    .replace("&", "&amp;")
    .replace("<", "&lt;")
    .replace(">", "&gt;")
}