package io.github.architectplatform.cli.graph

import io.github.architectplatform.cli.dto.TaskPlanDTO
import io.github.architectplatform.cli.dto.TaskPlanStepDTO
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.writeText

class TaskGraphHtmlRenderer {
  fun render(graphName: String, plans: List<TaskPlanDTO>): String {
    val steps = plans.flatMap { it.steps }
    val mermaid = renderMermaid(graphName, steps)
    val escapedTitle = escapeHtml(graphName)
    return """
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>$escapedTitle Task Graph</title>
    <script type="module">
      import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
      mermaid.initialize({ startOnLoad: true, securityLevel: 'loose' });
    </script>
    <style>
      body {
        font-family: "Iosevka", "IBM Plex Sans", monospace;
        margin: 0;
        padding: 32px;
        background: linear-gradient(180deg, #f7f3ea 0%, #efe7d6 100%);
        color: #1d1b18;
      }
      main {
        max-width: 1400px;
        margin: 0 auto;
      }
      h1 {
        margin: 0 0 12px;
        font-size: 32px;
      }
      p {
        margin: 0 0 24px;
        color: #5c5141;
      }
      .card {
        background: rgba(255, 255, 255, 0.72);
        border: 1px solid rgba(76, 62, 43, 0.15);
        border-radius: 24px;
        padding: 24px;
        box-shadow: 0 20px 50px rgba(80, 58, 30, 0.12);
        overflow: auto;
      }
    </style>
  </head>
  <body>
    <main>
      <h1>$escapedTitle Task Graph</h1>
      <p>Generated by Architect from the current project's task dependency DAG.</p>
      <section class="card">
        <pre class="mermaid">
$mermaid
        </pre>
      </section>
    </main>
  </body>
</html>
""".trimIndent() + "\n"
  }

  fun writeTempFile(graphName: String, plans: List<TaskPlanDTO>): Path {
    val outputPath = Files.createTempFile("architect-graph-", ".html")
    outputPath.writeText(render(graphName, plans))
    return outputPath
  }

  private fun renderMermaid(graphName: String, steps: List<TaskPlanStepDTO>): String {
    val nodes = linkedMapOf<String, TaskPlanStepDTO>()
    steps.sortedBy { it.id }.forEach { step -> nodes.putIfAbsent(step.id, step) }
    steps.flatMap { it.depends }.sorted().forEach { dependencyId ->
      nodes.putIfAbsent(
        dependencyId,
        TaskPlanStepDTO(id = dependencyId, description = "", phase = null, depends = emptyList(), batch = 0),
      )
    }

    val mermaidIds = nodes.keys.withIndex().associate { (index, id) -> id to "task_$index" }
    val lines = mutableListOf("---", "title: ${graphName} task graph", "---", "flowchart LR")

    nodes.forEach { (id, step) ->
      val label = buildLabel(step)
      lines += "  ${mermaidIds.getValue(id)}[\"$label\"]"
    }

    steps
      .flatMap { step -> step.depends.map { dependencyId -> dependencyId to step.id } }
      .distinct()
      .sortedWith(compareBy<Pair<String, String>> { it.first }.thenBy { it.second })
      .forEach { (dependencyId, taskId) ->
        lines += "  ${mermaidIds.getValue(dependencyId)} --> ${mermaidIds.getValue(taskId)}"
      }

    return lines.joinToString("\n")
  }

  private fun buildLabel(step: TaskPlanStepDTO): String {
    return listOfNotNull(
      step.id,
      step.phase?.takeIf { it.isNotBlank() }?.let { "[$it]" },
      step.description.takeIf { it.isNotBlank() },
    ).joinToString("<br/>") { escapeMermaid(it) }
  }

  private fun escapeMermaid(value: String): String = value
    .replace("\"", "&quot;")
    .replace("<", "&lt;")
    .replace(">", "&gt;")

  private fun escapeHtml(value: String): String = value
    .replace("&", "&amp;")
    .replace("<", "&lt;")
    .replace(">", "&gt;")
}